### ISSUE TITLE
请问路由功能怎么用？

### ISSUE THREAD

**Issue by wuzhihang0** [charleylla/charley-vue-multi#1]
如题，请问路由功能怎么用，然后在多面面中还可以有单页面的混合吗？

**Comment by charleylla** [comment]
每个页面就是一个路由，要新增路由，在 ```src/page``` 下添加页面即可

**Comment by Akesure** [comment]
@charleylla npm run dev 匹配不上路由。/home没有。

**Comment by Akesure** [comment]
为什么什么项目都在 http://192.168.0.102/

**Comment by charleylla** [comment]
@Akesure 请再详细描述下你的问题，我不太明白

**Comment by zhangbinzhbb** [comment]
默认打开了 http://172.29.201.197:8080/ 这个page-index页面， http://172.29.201.197:8080/home 打开页面还是 index页面，这个路由跳转需要怎么使用

**Comment by charleylla** [comment]
@zhangbinzhbb 你好 页面是 /index.html，需要加上 html 后缀，这个是生成的多页页面，需要带上后缀访问
